import { Product, CarouselSlide } from "./types";

export const carouselSlides: CarouselSlide[] = [
  {
    id: 1,
    title: "Moldes que\nInspiran Magia",
    subtitle: "Transforma tus creaciones con nuestros moldes artesanales de la más alta calidad. Diseños únicos para repostería y manualidades.",
    cta: "Ver Colección",
    gradient: "from-pink-400 via-rose-300 to-amber-300",
    emoji: "🎂",
    accent: "#E91E8C",
  },
  {
    id: 2,
    title: "Nuevos Diseños\nde Temporada",
    subtitle: "Descubre nuestros moldes exclusivos para cada ocasión especial. Bodas, cumpleaños, Navidad y mucho más.",
    cta: "Explorar Novedades",
    gradient: "from-violet-400 via-purple-300 to-pink-300",
    emoji: "✨",
    accent: "#7C3AED",
  },
  {
    id: 3,
    title: "Artesanía con\nCorazón Propio",
    subtitle: "Cada molde está diseñado con amor y precisión para que tus creaciones sean memorables e irrepetibles.",
    cta: "Conoce Más",
    gradient: "from-teal-400 via-cyan-300 to-sky-300",
    emoji: "💝",
    accent: "#0EA5E9",
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Molde Corazón Rizado",
    description: "Perfecto para tortas románticas y san valentín. Bordes texturizados que dan un acabado profesional.",
    price: 28000,
    category: "Repostería",
    badge: "Más Vendido",
    badgeColor: "bg-rose-500",
    emoji: "❤️",
    colors: ["from-rose-400", "to-pink-300"],
  },
  {
    id: 2,
    name: "Molde Floral 3D",
    description: "Crea flores tridimensionales impresionantes para decorar tortas y cupcakes con estilo.",
    price: 35000,
    category: "Decoración",
    badge: "Nuevo",
    badgeColor: "bg-violet-500",
    emoji: "🌸",
    colors: ["from-violet-400", "to-purple-300"],
  },
  {
    id: 3,
    name: "Set Estrellas Navideñas",
    description: "Juego de 6 moldes con diferentes tamaños de estrellas. Ideal para galletas y panes navideños.",
    price: 42000,
    category: "Navidad",
    emoji: "⭐",
    colors: ["from-amber-400", "to-yellow-300"],
  },
  {
    id: 4,
    name: "Molde Unicornio",
    description: "El favorito de las fiestas infantiles. Crea tortas mágicas con este molde detallado.",
    price: 52000,
    category: "Infantil",
    badge: "Tendencia",
    badgeColor: "bg-pink-500",
    emoji: "🦄",
    colors: ["from-pink-400", "to-rose-300"],
  },
  {
    id: 5,
    name: "Molde Mandala Geométrico",
    description: "Diseño intrincado para crear postres artísticos. Perfecto para repostería creativa y artesanía.",
    price: 38000,
    category: "Arte",
    emoji: "🔮",
    colors: ["from-teal-400", "to-cyan-300"],
  },
  {
    id: 6,
    name: "Kit Letras del Abecedario",
    description: "26 moldes de letras para personalizar tortas, galletas y decoraciones con nombres y mensajes.",
    price: 65000,
    category: "Personalización",
    badge: "Kit",
    badgeColor: "bg-sky-500",
    emoji: "🔤",
    colors: ["from-sky-400", "to-blue-300"],
  },
  {
    id: 7,
    name: "Molde Mariposa Grande",
    description: "Alas detalladas para tortas de primavera y celebraciones. Incluye molde para el cuerpo.",
    price: 31000,
    category: "Naturaleza",
    emoji: "🦋",
    colors: ["from-emerald-400", "to-teal-300"],
  },
  {
    id: 8,
    name: "Molde Corona Real",
    description: "Para cumpleaños de princesas y reinas. Relieves detallados que simulan oro y piedras preciosas.",
    price: 45000,
    category: "Infantil",
    emoji: "👑",
    colors: ["from-amber-400", "to-orange-300"],
  },
  {
    id: 9,
    name: "Set Números 0-9",
    description: "Moldes de números grandes para tortas de cumpleaños. Material antiadherente premium.",
    price: 55000,
    category: "Cumpleaños",
    badge: "Popular",
    badgeColor: "bg-orange-500",
    emoji: "🔢",
    colors: ["from-orange-400", "to-amber-300"],
  },
  {
    id: 10,
    name: "Molde Cactus Artístico",
    description: "Tendencia boho-chic para eventos modernos. Crea postres con personalidad y estilo único.",
    price: 29000,
    category: "Tendencia",
    badge: "Nuevo",
    badgeColor: "bg-green-500",
    emoji: "🌵",
    colors: ["from-green-400", "to-emerald-300"],
  },
  {
    id: 11,
    name: "Molde Arco de Novia",
    description: "El complemento perfecto para bodas y compromisos. Diseño elegante con detalles florales.",
    price: 48000,
    category: "Bodas",
    emoji: "💒",
    colors: ["from-pink-300", "to-rose-200"],
  },
  {
    id: 12,
    name: "Kit Navidad Completo",
    description: "Santa, árbol, reno y estrella. Todo lo que necesitas para la repostería navideña en un solo set.",
    price: 78000,
    category: "Navidad",
    badge: "Kit Premium",
    badgeColor: "bg-red-500",
    emoji: "🎄",
    colors: ["from-red-400", "to-rose-300"],
  },
  {
    id: 13,
    name: "Molde Hexagonal Panal",
    description: "Diseño geométrico moderno. Ideal para tartas de boda contemporáneas y eventos minimalistas.",
    price: 33000,
    category: "Moderno",
    emoji: "🍯",
    colors: ["from-yellow-400", "to-amber-300"],
  },
  {
    id: 14,
    name: "Molde Dinosaurio Rex",
    description: "Para los pequeños amantes de los dinosaurios. Crea tortas prehistóricas y divertidas.",
    price: 37000,
    category: "Infantil",
    emoji: "🦕",
    colors: ["from-lime-400", "to-green-300"],
  },
  {
    id: 15,
    name: "Molde Castillo de Hadas",
    description: "Tortas de cuento de hadas con este detallado molde de castillo con torres y ventanas.",
    price: 62000,
    category: "Infantil",
    badge: "Exclusivo",
    badgeColor: "bg-purple-500",
    emoji: "🏰",
    colors: ["from-purple-400", "to-violet-300"],
  },
  {
    id: 16,
    name: "Set Frutas Tropicales",
    description: "Sandía, piña, mango y más. Para postres tropicales y fiestas de verano vibrantes.",
    price: 44000,
    category: "Verano",
    emoji: "🍍",
    colors: ["from-pink-400", "to-orange-300"],
  },
  {
    id: 17,
    name: "Molde Luna y Estrellas",
    description: "Para amantes del cosmos. Crea galaxias comestibles con este set de moldes celestiales.",
    price: 36000,
    category: "Fantasía",
    badge: "Nuevo",
    badgeColor: "bg-indigo-500",
    emoji: "🌙",
    colors: ["from-indigo-400", "to-violet-300"],
  },
  {
    id: 18,
    name: "Molde Cupcake Gigante",
    description: "Crea un cupcake de tamaño gigante perfecto para cumpleaños y celebraciones especiales.",
    price: 41000,
    category: "Repostería",
    emoji: "🧁",
    colors: ["from-pink-400", "to-fuchsia-300"],
  },
  {
    id: 19,
    name: "Kit Herramientas Chocolatero",
    description: "Moldes especiales para chocolate: bombones, figuras y tabletas con diseños artísticos.",
    price: 71000,
    category: "Chocolate",
    badge: "Premium",
    badgeColor: "bg-yellow-700",
    emoji: "🍫",
    colors: ["from-amber-600", "to-yellow-400"],
  },
  {
    id: 20,
    name: "Molde Rosca Navideña",
    description: "Tradicional molde acanalado para roscas y bundt cakes. Patrón floral en toda la superficie.",
    price: 39000,
    category: "Navidad",
    emoji: "🍩",
    colors: ["from-red-400", "to-pink-300"],
  },
  {
    id: 21,
    name: "Molde Sirena y Mar",
    description: "Para las fiesteras del mar. Escamas detalladas, conchitas y cola de sirena.",
    price: 53000,
    category: "Fantasía",
    badge: "Tendencia",
    badgeColor: "bg-teal-500",
    emoji: "🧜",
    colors: ["from-teal-400", "to-cyan-300"],
  },
  {
    id: 22,
    name: "Set Letras Script",
    description: "Letras en estilo caligrafía cursiva para tortas elegantes y personalizadas.",
    price: 67000,
    category: "Personalización",
    emoji: "✍️",
    colors: ["from-rose-400", "to-pink-300"],
  },
  {
    id: 23,
    name: "Molde Panda Kawaii",
    description: "Tierno molde de panda estilo japonés. Perfecto para fiestas temáticas y niños.",
    price: 34000,
    category: "Infantil",
    emoji: "🐼",
    colors: ["from-gray-300", "to-slate-200"],
  },
  {
    id: 24,
    name: "Kit Pascua Completo",
    description: "Conejitos, huevos y flores. Todo lo que necesitas para la temporada de Pascua.",
    price: 58000,
    category: "Pascua",
    badge: "Temporada",
    badgeColor: "bg-green-500",
    emoji: "🐣",
    colors: ["from-lime-400", "to-yellow-300"],
  },
];
